#' Table 15.26 Hypothetical Data Set Generated by the Model Y = -1 + 3X + e
#'
#' Hypothetical Data Set Generated by the Model Y = -1 + 3X + e
#'
#' @format A [tibble][tibble::tibble-package] with `r nrow(table_15_26)` rows and
#' `r ncol(table_15_26)` variables:
#' \itemize{
#'   \item \strong{y:} y = -1 + 3x + e
#'   \item \strong{y_star:} = 1 se y > 0; 0 otherwise
#'   \item \strong{x}
#' }
#'
#' @source  William E. Becker and Donald M. Waldman, “A Graphical Interpretation
#' of Probit Coefﬁcients,” Journal of Economic Education, Fall 1989, Table 1, p. 373.
"table_15_26"
